CREATE DATABASE KC;
SHOW DATABASES;
USE KC;

CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL
);

INSERT INTO Worker VALUES
(1, 'Anu', 'Pallavi', 'HR', 95000.00),
(2, 'Shreyas', 'Rahul', 'Finance', 105000.00),
(3, 'Aniket', 'Verma', 'IT', 97000.00),
(4, 'Sundar', 'Pichai', 'Marketing', 102000.00),
(5, 'Lakshmi', 'Rai', 'HR', 79000.00),
(6, 'Leo', 'Das', 'IT', 108000.00),
(7, 'Vignesh', 'Kanna', 'Admin', 88000.00),
(8, 'Gopi', 'Krishna', 'Finance', 110000.00);

SELECT * FROM Worker;

SELECT * FROM Worker
WHERE DEPARTMENT = 'IT' AND SALARY > 100000;

SELECT * FROM Worker
WHERE DEPARTMENT = 'HR' OR SALARY < 80000;

SELECT * FROM Worker
WHERE NOT DEPARTMENT = 'Finance';

SELECT * FROM Worker
WHERE SALARY > 90000 AND (DEPARTMENT = 'IT' OR DEPARTMENT = 'Finance');

SELECT * FROM Worker 
WHERE WORKER_ID IN (1,3,5,8) AND SALARY >= 10000;

SELECT * FROM Worker 
WHERE DEPARTMENT NOT IN ('HR','ADMIN') AND SALARY BETWEEN 70000 AND 300000;

SELECT * FROM WORKER WHERE FIRST_NAME LIKE 'V%' AND SALARY >= 200000;

SELECT * FROM WORKER WHERE DEPARTMENT NOT IN ('ADMIN') AND SALARY <100000; 

SELECT AVG(SALARY) FROM WORKER WHERE DEPARTMENT='ADMIN'; 

SELECT MIN(SALARY) AS Minimum_Salary FROM Worker;

SELECT * FROM Worker
WHERE SALARY = (SELECT MAX(SALARY) FROM Worker);

SELECT AVG(SALARY) AS Avg_Admin_Salary
FROM Worker
WHERE DEPARTMENT = 'Admin';

SELECT SUM(SALARY) AS Total_HR_Admin_Salary
FROM Worker
WHERE DEPARTMENT IN ('HR', 'Admin');

SELECT SUM(SALARY) AS Total_HR_Admin_Salary
FROM Worker
WHERE DEPARTMENT IN ('HR', 'Admin');

SELECT COUNT(*) AS Count_V
FROM Worker
WHERE FIRST_NAME LIKE 'V%';

SELECT SUM(SALARY) AS Total_Salary_Range
FROM Worker
WHERE SALARY BETWEEN 50000 AND 200000;

SELECT FIRST_NAME FROM Worker
UNION 
SELECT LAST_NAME FROM Worker;

SELECT FIRST_NAME, SALARY,
CASE 
    WHEN SALARY < 50000 THEN 'poor'
    WHEN SALARY BETWEEN 50000 AND 150000 THEN 'middle-class'
    ELSE 'rich'
END AS StatusBasedOnSalary
FROM WORKER;
